services:
  redis-broker:
    image: redis:7-alpine
    container_name: sync-redis
    ports:
      - "6380:6379"
    networks:
      - sync-net

  postgres-db:
    image: postgres:15-alpine
    container_name: sync-postgres
    environment:
      POSTGRES_USER: ubuntu_dev
      POSTGRES_PASSWORD: SecretPassword123
      POSTGRES_DB: synccode_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sync-net

  socket-engine:
    build: ./apps/backend-sockets
    container_name: sync-socket-engine
    restart: always
    ports:
      - "5001:5000"
    environment:
      REDIS_URL: "redis://redis-broker:6379"
      PORT: 5000
    depends_on:
      - redis-broker
    networks:
      - sync-net

  # Observability Layer: Time-Series Database Scraper
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: sync-prometheus
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090" # Fixed: Map external host port 9091 to container port 9090
    networks:
      - sync-net

  # Observability Layer: Graphical Visualization Dashboard
  grafana:
    image: grafana/grafana:10.0.0
    container_name: sync-grafana
    ports:
      - "3001:3000" # Maps Grafana to local port 3001
    depends_on:
      - prometheus
    networks:
      - sync-net

networks:
  sync-net:
    driver: bridge

volumes:
  pgdata: